DROP DATABASE IF EXISTS spectrum;

CREATE DATABASE spectrum;

USE spectrum;


CREATE TABLE Users (
  email VARCHAR(255) NOT NULL, 
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (email)
);

CREATE TABLE Messages (
  body VARCHAR(8000) NOT NULL, 
  senderEmail VARCHAR(255) NOT NULL,
  recipientEmail VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (senderEmail) REFERENCES Users(email),
  FOREIGN KEY (recipientEmail) REFERENCES Users(email),
  id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);
