DROP DATABASE IF EXISTS spectrum;

CREATE DATABASE spectrum;

USE spectrum;

CREATE TABLE Users (
  email VARCHAR(255) NOT NULL, 
  password VARCHAR(255) NOT NULL, 
  userName VARCHAR(255) NOT NULL, 
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

CREATE TABLE Messages (
  body VARCHAR(8000) NOT NULL, 
  senderId INT NOT NULL,
  recipientId INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (senderId) REFERENCES Users(id),
  FOREIGN KEY (recipientId) REFERENCES Users(id),
  id int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);
